-- =====================================================================
-- Load Extracted Graph Data from CSV Files
-- =====================================================================
-- This script loads the CSV files generated by extractPDF/extract_pdf_to_graph.py
-- into Oracle Database and creates the property graph.
--
-- Prerequisites:
-- 1. Oracle 23ai container running with volume mount to extractPDF/output
-- 2. CSV files exist at /opt/oracle/graph_data/ in container
--
-- Usage:
--   sqlplus system/oracle@localhost:1521/FREEPDB1 @load_extracted_graph_data.sql
-- Or from inside container:
--   docker exec -i oracle23ai sqlplus system/oracle@FREEPDB1 @/path/to/load_extracted_graph_data.sql
-- =====================================================================

SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON

PROMPT ======================================================================
PROMPT Step 1: Create Oracle Directory Object
PROMPT ======================================================================

CREATE OR REPLACE DIRECTORY extractpdf_dir AS '/opt/oracle/graph_data';

PROMPT Directory created successfully.
PROMPT

PROMPT ======================================================================
PROMPT Step 2: Create Graph Tables (Nodes and Edges)
PROMPT ======================================================================

-- Drop existing tables if they exist
BEGIN
    FOR rec IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'PAPERS_NODES', 'TREATMENTS_NODES', 'CONDITIONS_NODES',
        'MENTIONS_EDGES', 'TREATS_EDGES',
        'PAPERS_NODES_EXT', 'TREATMENTS_NODES_EXT', 'CONDITIONS_NODES_EXT',
        'MENTIONS_EDGES_EXT', 'TREATS_EDGES_EXT'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- Papers Nodes Table
CREATE TABLE papers_nodes (
    node_id          NUMBER PRIMARY KEY,
    filename         VARCHAR2(200) NOT NULL,
    title            VARCHAR2(500),
    publication_date DATE
);

PROMPT Created table: PAPERS_NODES
PROMPT

-- Treatments Nodes Table
CREATE TABLE treatments_nodes (
    node_id         NUMBER PRIMARY KEY,
    entity_name     VARCHAR2(200) NOT NULL,
    treatment_type  VARCHAR2(100)
);

PROMPT Created table: TREATMENTS_NODES
PROMPT

-- Conditions Nodes Table
CREATE TABLE conditions_nodes (
    node_id     NUMBER PRIMARY KEY,
    name        VARCHAR2(200) NOT NULL,
    icd10_code  VARCHAR2(20)
);

PROMPT Created table: CONDITIONS_NODES
PROMPT

-- MENTIONS Edges Table (Paper -> Treatment)
CREATE TABLE mentions_edges (
    edge_id       NUMBER PRIMARY KEY,
    from_node_id  NUMBER NOT NULL,
    to_node_id    NUMBER NOT NULL,
    CONSTRAINT fk_mentions_from FOREIGN KEY (from_node_id) REFERENCES papers_nodes(node_id),
    CONSTRAINT fk_mentions_to FOREIGN KEY (to_node_id) REFERENCES treatments_nodes(node_id)
);

PROMPT Created table: MENTIONS_EDGES
PROMPT

-- TREATS Edges Table (Treatment -> Condition)
CREATE TABLE treats_edges (
    edge_id       NUMBER PRIMARY KEY,
    from_node_id  NUMBER NOT NULL,
    to_node_id    NUMBER NOT NULL,
    CONSTRAINT fk_treats_from FOREIGN KEY (from_node_id) REFERENCES treatments_nodes(node_id),
    CONSTRAINT fk_treats_to FOREIGN KEY (to_node_id) REFERENCES conditions_nodes(node_id)
);

PROMPT Created table: TREATS_EDGES
PROMPT

PROMPT ======================================================================
PROMPT Step 3: Create External Tables for CSV Loading
PROMPT ======================================================================

-- External table for papers_nodes.csv
CREATE TABLE papers_nodes_ext (
    node_id NUMBER,
    filename VARCHAR2(200),
    title VARCHAR2(500),
    publication_date DATE
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY extractpdf_dir
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
        (
            node_id,
            filename,
            title,
            publication_date DATE "YYYY-MM-DD"
        )
    )
    LOCATION ('papers_nodes.csv')
)
REJECT LIMIT UNLIMITED;

PROMPT Created external table: PAPERS_NODES_EXT
PROMPT

-- External table for treatments_nodes.csv
CREATE TABLE treatments_nodes_ext (
    node_id NUMBER,
    entity_name VARCHAR2(200),
    treatment_type VARCHAR2(100)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY extractpdf_dir
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('treatments_nodes.csv')
)
REJECT LIMIT UNLIMITED;

PROMPT Created external table: TREATMENTS_NODES_EXT
PROMPT

-- External table for conditions_nodes.csv
CREATE TABLE conditions_nodes_ext (
    node_id NUMBER,
    name VARCHAR2(200),
    icd10_code VARCHAR2(20)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY extractpdf_dir
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('conditions_nodes.csv')
)
REJECT LIMIT UNLIMITED;

PROMPT Created external table: CONDITIONS_NODES_EXT
PROMPT

-- External table for mentions_edges.csv
CREATE TABLE mentions_edges_ext (
    edge_id NUMBER,
    from_node_id NUMBER,
    to_node_id NUMBER
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY extractpdf_dir
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('mentions_edges.csv')
)
REJECT LIMIT UNLIMITED;

PROMPT Created external table: MENTIONS_EDGES_EXT
PROMPT

-- External table for treats_edges.csv
CREATE TABLE treats_edges_ext (
    edge_id NUMBER,
    from_node_id NUMBER,
    to_node_id NUMBER
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY extractpdf_dir
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('treats_edges.csv')
)
REJECT LIMIT UNLIMITED;

PROMPT Created external table: TREATS_EDGES_EXT
PROMPT

PROMPT ======================================================================
PROMPT Step 4: Load Data from CSV Files into Permanent Tables
PROMPT ======================================================================

-- Load papers
INSERT INTO papers_nodes SELECT * FROM papers_nodes_ext;
PROMPT Loaded papers_nodes: &SQL%ROWCOUNT rows
COMMIT;

-- Load treatments
INSERT INTO treatments_nodes SELECT * FROM treatments_nodes_ext;
PROMPT Loaded treatments_nodes: &SQL%ROWCOUNT rows
COMMIT;

-- Load conditions
INSERT INTO conditions_nodes SELECT * FROM conditions_nodes_ext;
PROMPT Loaded conditions_nodes: &SQL%ROWCOUNT rows
COMMIT;

-- Load MENTIONS edges
INSERT INTO mentions_edges SELECT * FROM mentions_edges_ext;
PROMPT Loaded mentions_edges: &SQL%ROWCOUNT rows
COMMIT;

-- Load TREATS edges
INSERT INTO treats_edges SELECT * FROM treats_edges_ext;
PROMPT Loaded treats_edges: &SQL%ROWCOUNT rows
COMMIT;

PROMPT
PROMPT Data loading complete!
PROMPT

PROMPT ======================================================================
PROMPT Step 5: Verify Data Loaded
PROMPT ======================================================================

SELECT 'Papers' AS table_name, COUNT(*) AS row_count FROM papers_nodes
UNION ALL
SELECT 'Treatments', COUNT(*) FROM treatments_nodes
UNION ALL
SELECT 'Conditions', COUNT(*) FROM conditions_nodes
UNION ALL
SELECT 'MENTIONS edges', COUNT(*) FROM mentions_edges
UNION ALL
SELECT 'TREATS edges', COUNT(*) FROM treats_edges;

PROMPT
PROMPT ======================================================================
PROMPT Step 6: Create Property Graph
PROMPT ======================================================================

-- Drop existing graph if it exists
BEGIN
    EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH medical_literature_kg';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -40927 THEN  -- ORA-40927: property graph does not exist
            RAISE;
        END IF;
END;
/

CREATE PROPERTY GRAPH medical_literature_kg
    VERTEX TABLES (
        papers_nodes AS Paper
            KEY (node_id)
            PROPERTIES (node_id, filename, title, publication_date),
        treatments_nodes AS Treatment
            KEY (node_id)
            PROPERTIES (node_id, entity_name, treatment_type),
        conditions_nodes AS Condition
            KEY (node_id)
            PROPERTIES (node_id, name, icd10_code)
    )
    EDGE TABLES (
        mentions_edges AS MENTIONS
            KEY (edge_id)
            SOURCE KEY (from_node_id) REFERENCES Paper (node_id)
            DESTINATION KEY (to_node_id) REFERENCES Treatment (node_id)
            PROPERTIES (edge_id),
        treats_edges AS TREATS
            KEY (edge_id)
            SOURCE KEY (from_node_id) REFERENCES Treatment (node_id)
            DESTINATION KEY (to_node_id) REFERENCES Condition (node_id)
            PROPERTIES (edge_id)
    );

PROMPT Property graph MEDICAL_LITERATURE_KG created successfully!
PROMPT

PROMPT ======================================================================
PROMPT Step 7: Test Graph Query
PROMPT ======================================================================

PROMPT Query: Show all treatments that treat Type 2 Diabetes
PROMPT

SELECT t.entity_name AS treatment, c.name AS condition
FROM GRAPH_TABLE (
    medical_literature_kg
    MATCH (t:Treatment)-[:TREATS]->(c:Condition)
    WHERE c.name = 'Type 2 Diabetes'
    COLUMNS (t.entity_name, c.name)
)
ORDER BY t.entity_name;

PROMPT
PROMPT ======================================================================
PROMPT SUCCESS! Graph data loaded and ready to use.
PROMPT ======================================================================
PROMPT
PROMPT Next steps:
PROMPT 1. Load patient data (relational table) - see oracle-setup/01_create_relational_tables.sql
PROMPT 2. Run hybrid queries - see oracle-setup/05_test_queries.sql
PROMPT
PROMPT ======================================================================
